Define kfp as extra and update error messages
ml6team/fondant pull request #361
Opened 2023-08-16 12:11 UTC by GeorgesLorre

2023-08-16 12:31 UTC, PhilippeMoussalli approved these changes
Thanks!

2023-08-17 07:55 UTC, RobbeSneyders requested changes

2023-08-17 09:57 UTC, GeorgesLorre commented on src/fondant/compiler.py
> +                     you can install it with `pip install --extras kfp`"""
fixed

2023-08-17 13:40 UTC, RobbeSneyders approved these changes
Thanks @GeorgesLorre!

2023-08-17 13:40 UTC, merged