captions+clip
ml6team/fondant pull request #381
Opened 2023-08-23 12:41 UTC by alexanderremmerie

2023-08-23 12:43 UTC, NielsRogge approved these changes

2023-08-23 20:03 UTC, RobbeSneyders requested changes
Thanks @alexanderremmerie 

Can you just revert all the commit hashes in the component specs?

2023-08-24 06:26 UTC, NielsRogge commented
@RobbeSneyders I've reverted the commit hashes, but I have not yet had an experience where the dev tags work out of the box. I always need to rebuild the Docker images because the dev ones don't work

2023-08-24 07:25 UTC, RobbeSneyders commented
We might want to implement this: https://github.com/ml6team/fondant/issues/365
Also for the local runner.

2023-08-24 07:26 UTC, RobbeSneyders commented on examples/pipelines/datacomp/simple_pipeline.py
> +    # base_path="/Users/nielsrogge/Documents/fondant_artifacts_datacomp",
```suggestion
```

2023-08-24 07:26 UTC, RobbeSneyders commented on examples/pipelines/datacomp/simple_pipeline.py
> +        # "n_rows_to_load": 100,
```suggestion
        "n_rows_to_load": 100,
```

2023-08-24 07:27 UTC, RobbeSneyders approved these changes

2023-08-24 07:27 UTC, merged