Add screenshots data explorer
ml6team/fondant pull request #555
Opened 2023-10-26 14:34 UTC by mrchtr

fix #496

2023-10-26 14:39 UTC, PhilippeMoussalli approved these changes
Nice! Thanks Matthias

2023-10-27 13:00 UTC, RobbeSneyders requested changes
Thanks @mrchtr!

One small typo in one of the urls. Also, I think we can use relative urls here, which should be a bit more robust.

Can you also move the `Data Explorer UI` section to the top and the `How to use?` to the bottom?

2023-10-27 13:00 UTC, RobbeSneyders commented on docs/data_explorer.md
> +![data explorer](https://github.com/ml6team/fondant/blob/main/docs/art/data_explorer/data_explorers.png?raw=true)
```suggestion
![data explorer](https://github.com/ml6team/fondant/blob/main/docs/art/data_explorer/data_explorer.png?raw=true)
```

2023-10-27 13:10 UTC, mrchtr commented
> Also, I think we can use relative urls here, which should be a bit more robust.

Not sure if this will work. The images where broken some weeks ago. Then we started to replace the relative links with the urls to the images.

2023-10-27 13:13 UTC, RobbeSneyders commented
> Not sure if this will work. The images where broken some weeks ago. Then we started to replace the relative links with the urls to the images.

This should only be the case on the main page, since we insert the README there and the urls need to be relevant to different directories on the site vs Github.

2023-10-27 13:58 UTC, RobbeSneyders approved these changes

2023-10-27 13:58 UTC, merged